name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
        with:
          use_cspell_files: true
